/**
 * Generates docs/index.html - the landing page for the published site.
 *
 * Generated rather than hand-written for the same reason every other artefact
 * here is: a hand-listed index of 21 skills goes stale the first time someone
 * adds one, and a site that omits a skill is worse than no site, because a
 * reader trusts it. `npm run check` fails when the committed page no longer
 * matches the skills on disk.
 *
 * Install commands are parsed out of .agents/install-block.md rather than
 * restated, because that file is the single source of truth for installation
 * language and two differently-worded copies is how people run the wrong one.
 *
 * Usage:
 *   node scripts/build-site.mjs           write docs/index.html
 *   node scripts/build-site.mjs --check   fail if the committed page is stale
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync, realpathSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ROOT, loadSkills, PROMOTED, BUCKET_BLURB } from "./lib/skills.mjs";

export const SITE_PAGE = "docs/index.html";
export const SITE_DATA = "docs/_data/skills.yml";
const BANNER = "Generated by scripts/build-site.mjs. Do not edit by hand; run `npm run build`.";

const REPO = "https://github.com/RagnarPitla/microsoft-agent-skills";
const LINKS = [
  ["GitHub", "https://github.com/RagnarPitla"],
  ["LinkedIn", "https://www.linkedin.com/in/ragnarpitla"],
  ["YouTube", "https://www.youtube.com/@RagnarPitla"],
  ["RBuild.ai", "https://rbuild.ai"],
];
const TAGLINE = "Hard-won practice for building agents across the Microsoft ecosystem.";

const esc = (s) =>
  String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/**
 * Pull the fenced command blocks out of .agents/install-block.md, keyed by its
 * `## ` headings. Parsed rather than duplicated so the site cannot drift from
 * the wording the README is also required to match.
 */
export function parseInstallBlock(md) {
  const out = new Map();
  const sections = String(md).split(/^## /m).slice(1);
  for (const section of sections) {
    const name = section.slice(0, section.indexOf("\n")).trim();
    const blocks = [...section.matchAll(/```[a-z]*\n([\s\S]*?)```/g)].map((m) => m[1].trim());
    if (blocks.length) out.set(name, blocks);
  }
  return out;
}

const INSTALL_NOTES = {
  "Claude Code": "The repo is its own single-plugin marketplace, so registering it and installing from it are two steps. The name appears twice because the plugin and the marketplace that carries it share a name. That is correct, not a typo.",
  "GitHub Copilot": "Copilot reads the Agent Skills open standard natively, the same SKILL.md format this repo is written in, in VS Code, the Copilot CLI and the Copilot cloud agent.",
  Codex: "Codex reads the same SKILL.md standard, from <name>/SKILL.md directories under ~/.codex/skills. The generated tree is already in that shape.",
  Cursor: "Generated rules, ready to copy into a project.",
};

const STEPS = [
  ["Install once", "Clone the repo or add it as a plugin. Every skill is a Markdown file, so there is nothing to run and nothing to keep in sync."],
  ["Ask, or just work", "Three skills wait to be asked, because an interview that starts itself is worse than no interview. The other eighteen load themselves when the task matches."],
  ["It follows a method", "A skill is not a prompt. It carries the order to do things in, the questions to ask, and the failure it is written to prevent."],
  ["The gates keep it honest", "Every claim carries the date it was last checked against Microsoft's docs, and every link is re-tested on a schedule."],
];

const FAQ = [
  ["Do I need Claude to use these?", "No. GitHub Copilot is the primary target, and Codex and Cursor are peers rather than afterthoughts. Every skill is plain Markdown with no harness-specific assumptions, so any tool that can read a file into context can run them."],
  ["What is a skill, exactly?", "A Markdown file with front matter, holding the method for one job: what to ask, what order to do it in, and what goes wrong if you skip a step. It is closer to a checklist written by someone who has done the work than to a prompt."],
  ["Why are the categories named after verbs, not Microsoft products?", "Because Microsoft renames its products constantly. A folder called copilot-studio would be wrong within a year, and a skill filed under a renamed product becomes unfindable. Products appear inside a skill, never as the top-level taxonomy."],
  ["How do I know the technical detail is right?", "Every skill records the date its claims were last read against Microsoft's documentation, and one line on where the knowledge came from. Perishable claims carry their own review date and the build fails when one goes stale. Where something could not be verified, the skill says so instead of guessing."],
  ["Is any of this customer information?", "No. Nothing here names a customer, carries data from a customer tenant, or describes anything Microsoft has not announced publicly. Worked examples use invented companies and synthetic data, and a scrub gate runs before anything is published."],
  ["Can I use these commercially?", "Yes. MIT licensed. Fork it, copy one skill out of it, or rewrite them for your own stack."],
];

function skillCard(s) {
  const badge = s.userInvoked
    ? '<span class="badge you">You invoke it</span>'
    : '<span class="badge auto">Automatic</span>';
  return `          <a class="skill" href="${esc(s.bucket)}/${esc(s.name)}.html">
            <h3>${esc(s.displayName || s.name)}</h3>
            <p>${esc(s.shortDescription || "")}</p>
            <footer><code>${esc(s.name)}</code>${badge}</footer>
          </a>`;
}

function bucketSection(bucket, skills) {
  const inBucket = skills.filter((s) => s.bucket === bucket);
  if (!inBucket.length) return "";
  const cards = inBucket
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(skillCard)
    .join("\n");
  return `        <div class="bucket" id="${esc(bucket)}">
          <div class="bucket-head">
            <span class="pill">${esc(bucket)}</span>
            <p>${esc(BUCKET_BLURB[bucket] || "")}</p>
          </div>
          <div class="skills">
${cards}
          </div>
        </div>`;
}

function installCard(name, blocks) {
  const cmds = blocks.map((b) => `<pre><code>${esc(b)}</code></pre>`).join("\n            ");
  return `          <article class="install">
            <h3>${esc(name)}</h3>
            <p>${esc(INSTALL_NOTES[name] || "")}</p>
            ${cmds}
          </article>`;
}

/**
 * The ordered list of promoted skills, as the layout needs it.
 * Ordered by bucket then name so "previous" and "next" walk the same sequence a
 * reader sees on the landing page.
 */
export function orderedSkills(skills) {
  return skills
    .filter((s) => s.promoted)
    .slice()
    .sort((a, b) => PROMOTED.indexOf(a.bucket) - PROMOTED.indexOf(b.bucket) || a.name.localeCompare(b.name));
}

/**
 * Emits docs/_data/skills.yml. The layout reads it to put a skill's invocation
 * model, bucket and source link on its page, so none of that is retyped into
 * the Markdown where it could drift from the skill it describes.
 */
export function buildSkillsData(skills) {
  const ordered = orderedSkills(skills);
  const lines = [`# ${BANNER}`];

  ordered.forEach((s, i) => {
    const prev = ordered[i - 1];
    const next = ordered[i + 1];
    const f = (k, v) => (v === undefined || v === null ? null : `  ${k}: ${JSON.stringify(v)}`);
    lines.push(
      [
        f("name", s.name),
        f("title", s.displayName || s.name),
        f("short", s.shortDescription || ""),
        f("bucket", s.bucket),
        f("user_invoked", Boolean(s.userInvoked)),
        f("url", `/${s.bucket}/${s.name}.html`),
        f("source", `${REPO}/blob/main/skills/${s.bucket}/${s.name}/SKILL.md`),
        prev && f("prev", prev.displayName || prev.name),
        prev && f("prev_url", `/${prev.bucket}/${prev.name}.html`),
        next && f("next", next.displayName || next.name),
        next && f("next_url", `/${next.bucket}/${next.name}.html`),
      ]
        .filter(Boolean)
        .join("\n")
        .replace(/^ {2}/, "- "),
    );
  });

  return `${lines.join("\n")}\n`;
}

export function buildSite(skills, installBlock) {
  const promoted = skills.filter((s) => s.promoted);
  const userInvoked = promoted.filter((s) => s.userInvoked).length;
  const buckets = PROMOTED.filter((b) => promoted.some((s) => s.bucket === b));

  const install = ["Claude Code", "GitHub Copilot", "Codex", "Cursor"]
    .filter((n) => installBlock.has(n))
    .map((n) => installCard(n, installBlock.get(n).slice(0, 1)))
    .join("\n");

  const steps = STEPS.map(
    ([title, body], i) => `          <li>
            <span class="num">${i + 1}</span>
            <h3>${esc(title)}</h3>
            <p>${esc(body)}</p>
          </li>`,
  ).join("\n");

  const faq = FAQ.map(
    ([q, a]) => `          <details>
            <summary>${esc(q)}</summary>
            <p>${esc(a)}</p>
          </details>`,
  ).join("\n");

  const footLinks = LINKS.map(([label, href]) => `        <a href="${href}">${esc(label)}</a>`).join("\n");

  return `<!doctype html>
<!-- ${BANNER} -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Microsoft Agent Skills - ${esc(TAGLINE)}</title>
<meta name="description" content="${esc(TAGLINE)}">
<meta property="og:title" content="Microsoft Agent Skills">
<meta property="og:description" content="${esc(TAGLINE)}">
<meta property="og:image" content="${REPO}/raw/main/docs/assets/readme-hero.png">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="assets/favicon.svg" type="image/svg+xml">
<link rel="stylesheet" href="assets/site.css">
</head>
<body>

<header class="nav">
  <div class="wrap nav-in">
    <a class="brand" href="./">
      <img src="assets/favicon.svg" alt="" width="22" height="22">
      <strong>Microsoft Agent Skills</strong>
      <span class="brand-note">${esc(TAGLINE.toLowerCase().replace(/\.$/, ""))}</span>
    </a>
    <nav class="nav-links">
      <a href="#how">How it works</a>
      <a href="#skills">Skills</a>
      <a href="#faq">FAQ</a>
      <a href="${REPO}">GitHub</a>
      <a class="btn dark" href="#install">Install</a>
    </nav>
  </div>
</header>

<main>

  <section class="hero">
    <div class="wrap hero-in">
      <div class="hero-copy">
        <h1>Agent skills for the Microsoft stack, written from real builds.</h1>
        <p class="lede">Most agent advice stops at the demo. These ${promoted.length} skills carry the part after that: the order to do things in, the questions worth asking before you build, and the failures that only show up once real users arrive.</p>
        <p class="lede">Plain Markdown, no harness lock-in. If your tool can read a file into context, it can run these.</p>
        <div class="cta">
          <a class="btn dark" href="#install">Install, it's free</a>
          <a class="btn" href="${REPO}">View the code on GitHub</a>
        </div>
        <p class="meta">Open source, MIT <span>&middot;</span> ${promoted.length} skills <span>&middot;</span> ${buckets.length} categories <span>&middot;</span> Copilot, Claude Code, Codex, Cursor</p>
      </div>
      <div class="hero-art">
        <img src="assets/readme-hero.png" alt="Microsoft Agent Skills by Ragnar Pitla - ${esc(TAGLINE)}">
      </div>
    </div>
  </section>

  <section class="band">
    <div class="wrap narrow">
      <h2>You have probably hit this</h2>
      <p>The agent demos beautifully. Then it goes to real users, and it answers a question three different ways in three sessions, cites a page that does not say what it claims, and nobody can tell you who owns it or what it costs to run.</p>
      <p>None of that is a model problem. It is the part of the work that happens after the demo, and it is the part almost nobody writes down. That is what is in here.</p>
    </div>
  </section>

  <section id="how">
    <div class="wrap">
      <h2>How it works</h2>
      <p class="sub">One collection, installed once, that your agent reaches into when the task calls for it.</p>
      <ol class="steps">
${steps}
      </ol>
    </div>
  </section>

  <section id="skills" class="band">
    <div class="wrap">
      <h2>The skill set</h2>
      <p class="sub">Grouped by what you are doing, not by which Microsoft product is involved. Products get renamed, and a skill filed under a renamed product becomes unfindable.</p>
      <div class="buckets">
${buckets.map((b) => bucketSection(b, promoted)).join("\n\n")}
      </div>
    </div>
  </section>

  <section id="invocation">
    <div class="wrap">
      <h2>Two kinds of skill</h2>
      <p class="sub">The difference is not cosmetic. It decides whether the agent may start something on your behalf.</p>
      <div class="two">
        <div>
          <span class="pill">${userInvoked} skills</span>
          <h3>You invoke it</h3>
          <p>Reachable only when you ask for it by name. Interviews, reviews and anything that should wait to be asked rather than firing on a keyword. An interview that starts itself is worse than no interview.</p>
        </div>
        <div>
          <span class="pill">${promoted.length - userInvoked} skills</span>
          <h3>Reached for automatically</h3>
          <p>The agent loads it when the task matches its description. That is why each description is written as a trigger, listing the situations it fires on, rather than as a summary of contents.</p>
        </div>
      </div>
    </div>
  </section>

  <section id="install" class="band">
    <div class="wrap">
      <h2>Install</h2>
      <p class="sub">Pick your harness. Each skill is the same <code>SKILL.md</code> underneath.</p>
      <div class="installs">
${install}
      </div>
      <p class="note">Using something else? Every skill is plain Markdown at <code>skills/&lt;bucket&gt;/&lt;name&gt;/SKILL.md</code>. Read the file directly, or point your tool at <code>skills/index.json</code>, which lists every skill with its trigger, invocation model and paths.</p>
    </div>
  </section>

  <section id="honest">
    <div class="wrap">
      <h2>An index, not just a collection</h2>
      <p class="sub">When Microsoft already solves something well, this repo routes you to them and says so.</p>
      <div class="two">
        <div>
          <h3>The registry</h3>
          <p><code>registry/microsoft-ecosystem.yaml</code> catalogues the official and community repos worth knowing. <code>registry/connectors.yaml</code> covers how to connect an agent to a given system. Star counts and archive flags are pulled from the GitHub API rather than typed in by hand, so they do not quietly go stale.</p>
        </div>
        <div>
          <h3>The checks</h3>
          <p>Every URL cited anywhere in the repo is re-tested on a schedule, because a link that 404s costs more trust than a missing page. Every dated claim has a review window, and the build fails when one expires.</p>
        </div>
      </div>
    </div>
  </section>

  <section id="faq" class="band">
    <div class="wrap narrow">
      <h2>Frequently asked questions</h2>
      <div class="faq">
${faq}
      </div>
    </div>
  </section>

</main>

<footer class="foot">
  <div class="wrap">
    <div class="foot-links">
${footLinks}
    </div>
    <p>Written by Ragnar Pitla, Principal PM on Microsoft's agentic team and founder of <a href="https://rbuild.ai">RBuild.ai</a>. These skills come out of real implementation work, which is why they are opinionated about order and blunt about what does not work. Everything customer-specific is scrubbed before it lands here.</p>
    <p class="fine">Views here are my own and do not represent Microsoft's official position. MIT licensed. This page is generated from the skills in the repository.</p>
  </div>
</footer>

</body>
</html>
`;
}

const realpathOrNull = (p) => {
  try {
    return realpathSync(p);
  } catch {
    return null;
  }
};
const invokedAs = process.argv[1] && realpathOrNull(path.resolve(process.argv[1]));
const isMain = Boolean(invokedAs) && invokedAs === realpathOrNull(fileURLToPath(import.meta.url));

if (isMain) {
  const skills = loadSkills();
  const installBlock = parseInstallBlock(readFileSync(path.join(ROOT, ".agents/install-block.md"), "utf8"));
  const artefacts = new Map([
    [SITE_PAGE, buildSite(skills, installBlock)],
    [SITE_DATA, buildSkillsData(skills)],
  ]);
  const count = skills.filter((s) => s.promoted).length;

  if (process.argv.includes("--check")) {
    const stale = [...artefacts].filter(([rel, content]) => {
      const abs = path.join(ROOT, rel);
      return (existsSync(abs) ? readFileSync(abs, "utf8") : null) !== content;
    });

    if (stale.length) {
      console.error("Site artefacts are out of date:\n");
      stale.forEach(([rel]) => console.error(`  stale: ${rel}`));
      console.error("\nRun `npm run build` and commit the result.");
      process.exit(1);
    }
    console.log(`Site artefacts up to date (${artefacts.size} files from ${count} skills).`);
    process.exit(0);
  }

  for (const [rel, content] of artefacts) {
    const abs = path.join(ROOT, rel);
    mkdirSync(path.dirname(abs), { recursive: true });
    writeFileSync(abs, content, "utf8");
  }
  console.log(`Built ${artefacts.size} site artefact(s) from ${count} promoted skill(s).`);
}
